import { Character, EquipmentItem, CombatValue } from '@/types/preciousdays/character';

// --- ヘルパー定数 ---
const EMPTY_COMBAT_VALUE: CombatValue = { modifier: 0 };

const EMPTY_EQUIPMENT: EquipmentItem = {
  name: '',
  weight: 0,
  hitMod: 0,
  damage: '',
  range: '',
  dodgeMod: 0,
  defenseMod: 0,
  magicDefense: 0,
  notes: '',
};

// --- 初期値 (新規作成用) ---
export const INITIAL_CHARACTER: Character = {
  system: 'preciousdays',
  id: '',
  playerName: '',
  characterName: '',
  masterName: '',
  isCopyProhibited: false,

  hp: { modifier: 0 },
  mp: { modifier: 0 },
  wp: { modifier: 0 },
  gl: 0,

  experience: 0,
  species: 'human',
  style: 'enchanter',
  element: 'earth',

  appearance: {
    age: '',
    gender: '',
    height: '',
    weight: '',
    hairColor: '',
    eyeColor: '',
    skinColor: '',
  },

  // 能力値 (Baseなし)
  abilities: {
    physical: { bonus: 0, otherModifier: 0, total: 0 },
    intellect: { bonus: 0, otherModifier: 0, total: 0 },
    mystic: { bonus: 0, otherModifier: 0, total: 0 },
    agility: { bonus: 0, otherModifier: 0, total: 0 },
    passion: { bonus: 0, otherModifier: 0, total: 0 },
    affection: { bonus: 0, otherModifier: 0, total: 0 },
  },

  origin: '',
  secret: '',
  future: '',

  // 戦闘値
  combatValues: {
    magic: { ...EMPTY_COMBAT_VALUE },
    dodge: { ...EMPTY_COMBAT_VALUE },
    defense: { ...EMPTY_COMBAT_VALUE },
  },

  // 特殊な判定
  specialChecks: {
    enemyLore: { ...EMPTY_COMBAT_VALUE },
    appraisal: { ...EMPTY_COMBAT_VALUE },
  },

  equipment: {
    rHand: { ...EMPTY_EQUIPMENT },
    lHand: { ...EMPTY_EQUIPMENT },
    head: { ...EMPTY_EQUIPMENT },
    body: { ...EMPTY_EQUIPMENT },
    accessory: { ...EMPTY_EQUIPMENT },
    guardian: { ...EMPTY_EQUIPMENT },
  },
  items: [{ id: 'i1', name: '', weight: 1, quantity: 1, notes: '' }],
  skills: [{ id: 's1', name: 'マナインフロー', level: 0, effect: '魔術が使用可能になる' }],
};

// --- ダミーデータ ---
export const DUMMY_CHARACTERS: Character[] = [
  // 1. ソウルインフューザー
  {
    ...INITIAL_CHARACTER,
    id: 'sample01',
    playerName: 'サンプル',
    characterName: 'ソウルインフューザー',
    isCopyProhibited: true,

    species: 'human',
    style: 'enchanter',
    element: 'wind',
    hp: { modifier: 0 },
    mp: { modifier: 0 },
    wp: { modifier: 1 },
    gl: 0,
    abilities: {
      physical: { bonus: 1, otherModifier: 0, total: 4 },
      intellect: { bonus: 0, otherModifier: 0, total: 2 },
      mystic: { bonus: 0, otherModifier: 0, total: 2 },
      agility: { bonus: 4, otherModifier: 0, total: 6 },
      passion: { bonus: 0, otherModifier: 0, total: 3 },
      affection: { bonus: 0, otherModifier: 2, total: 4 },
    },
    combatValues: {
      magic: { modifier: -1 },
      dodge: { modifier: 0 },
      defense: { modifier: 0 },
    },
    specialChecks: {
      enemyLore: { modifier: 0 },
      appraisal: { modifier: 0 },
    },
    skills: [
      { id: 's1', name: 'マナインフロー', level: 0, effect: '魔術が使用可能になる' },
      { id: 's2', name: '種族スキル：人間', level: 0, effect: 'WP+1（計算済）' },
      {
        id: 's3',
        name: 'エンチャントウェポン',
        level: 0,
        effect: 'メジャー。1MP。焦点具で攻撃。ダメージ+2D',
      },
      { id: 's4', name: 'インパクトブレイク', level: 0, effect: 'DR前。3MP。ダメージ+10' },
      {
        id: 's5',
        name: 'ライフエンチャント',
        level: 1,
        effect: 'セット/マイナー。1MP。自身のHPを2D+(GL×2)点回復',
      },
      { id: 's6', name: 'マジックパリー', level: 0, effect: 'DR後。3MP。ダメージを(GL)D+4点軽減' },
      { id: 's7', name: 'ウェポントルネード', level: 1, effect: 'マイナー。1MP。魔術判定に+3' },
      {
        id: 's8',
        name: 'フェイクアタック',
        level: 1,
        effect: 'セット。3MP。「近」の単体と【俊敏】対決。スタンを与える',
      },
    ],
    equipment: {
      ...INITIAL_CHARACTER.equipment,
      rHand: {
        name: 'ロングソード',
        weight: 6,
        hitMod: -1,
        damage: '+7',
        range: '至近',
        dodgeMod: 0,
        defenseMod: 0,
        magicDefense: 0,
        notes: '',
      },
      body: {
        name: 'ローブ',
        weight: 2,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
      guardian: {
        name: 'マナヴェール',
        weight: 0,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
    },
    items: [
      { id: 'i1', name: 'ヒールポーション', weight: 1, quantity: 1, notes: '' },
      { id: 'i2', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
      { id: 'i3', name: 'ヒールポーション', weight: 1, quantity: 1, notes: '' },
    ],
  },

  // 2. マジカルコンダクター
  {
    ...INITIAL_CHARACTER,
    id: 'sample02',
    playerName: 'サンプル',
    characterName: 'マジカルコンダクター',
    isCopyProhibited: true,
    species: 'elf',
    style: 'caster',
    element: 'dark',
    hp: { modifier: 0 },
    mp: { modifier: 0 },
    wp: { modifier: 0 },
    gl: 0,
    abilities: {
      physical: { bonus: 0, otherModifier: 0, total: 2 },
      intellect: { bonus: 0, otherModifier: 0, total: 5 },
      mystic: { bonus: 0, otherModifier: 0, total: 2 },
      agility: { bonus: 0, otherModifier: 0, total: 3 },
      passion: { bonus: 0, otherModifier: 0, total: 6 },
      affection: { bonus: 0, otherModifier: 0, total: 3 },
    },
    combatValues: {
      magic: { modifier: 0 },
      dodge: { modifier: 0 },
      defense: { modifier: 0 },
    },
    specialChecks: {
      enemyLore: { modifier: 0 },
      appraisal: { modifier: 0 },
    },
    skills: [
      { id: 's1', name: 'マナインフロー', level: 0, effect: '魔術が使用可能になる' },
      {
        id: 's2',
        name: '種族スキル：仙族',
        level: 0,
        effect: '命中判定後。達成値に+3。シナリオ1回',
      },
      { id: 's3', name: 'フルバースト', level: 0, effect: 'メジャー。1MP。「近」にダメージ2D+2' },
      { id: 's4', name: 'マジックシールド', level: 0, effect: 'DR後。3MP。ダメージ(GL)D+5点軽減' },
      { id: 's5', name: 'クラッシュバレット', level: 0, effect: 'DR前。4MP。ダメージ+12' },
      {
        id: 's6',
        name: 'ライフソング',
        level: 1,
        effect: 'セット/マイナー。1MP。HPを2D+(GL)点回復',
      },
      { id: 's7', name: 'アークブラスト', level: 1, effect: 'マイナー。4MP。攻撃を範囲に' },
      {
        id: 's8',
        name: 'ミラージュマジック',
        level: 1,
        effect: 'セット。3MP。「近」の単体と【知力】対決。スタンを与える',
      },
    ],
    equipment: {
      ...INITIAL_CHARACTER.equipment,
      rHand: {
        name: 'ワンド',
        weight: 1,
        hitMod: 0,
        damage: '+1',
        range: '至近',
        dodgeMod: 0,
        defenseMod: 0,
        magicDefense: 0,
        notes: '',
      },
      body: {
        name: 'ローブ',
        weight: 2,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
      guardian: {
        name: 'マナヴェール',
        weight: 0,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
    },
    items: [
      { id: 'i1', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
      { id: 'i2', name: 'ヒールポーション', weight: 1, quantity: 1, notes: '' },
      { id: 'i3', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
    ],
  },

  // 3. マークスメイジ
  {
    ...INITIAL_CHARACTER,
    id: 'sample03',
    playerName: 'サンプル',
    characterName: 'マークスメイジ',
    isCopyProhibited: true,
    species: 'angel',
    style: 'shooter',
    element: 'fire',
    hp: { modifier: 0 },
    mp: { modifier: 0 },
    wp: { modifier: 0 },
    gl: 0,
    abilities: {
      physical: { bonus: 0, otherModifier: 0, total: 2 },
      intellect: { bonus: 0, otherModifier: 0, total: 6 },
      mystic: { bonus: 0, otherModifier: 0, total: 3 },
      agility: { bonus: 0, otherModifier: 0, total: 4 },
      passion: { bonus: 0, otherModifier: 0, total: 3 },
      affection: { bonus: 0, otherModifier: 0, total: 3 },
    },
    combatValues: {
      magic: { modifier: 0 },
      dodge: { modifier: 0 },
      defense: { modifier: 0 },
    },
    specialChecks: {
      enemyLore: { modifier: 0 },
      appraisal: { modifier: 0 },
    },
    skills: [
      { id: 's1', name: 'マナインフロー', level: 0, effect: '魔術が使用可能になる' },
      {
        id: 's2',
        name: '種族スキル：天使',
        level: 0,
        effect: 'DR前。回復魔術のHP回復量に+2D。シナリオ1回',
      },
      { id: 's3', name: 'マジックアロー', level: 0, effect: 'メジャー。魔術値+2。ダメージ1D+4' },
      { id: 's4', name: 'チャージバレット', level: 0, effect: 'DR前。3MP。ダメージ+10' },
      {
        id: 's5',
        name: 'スナイピング',
        level: 0,
        effect: '命中判定後。5MP。命中判定のダイス1個の出目を6に',
      },
      { id: 's6', name: 'ヒットエンドラン', level: 1, effect: 'セット。2MP。ラウンド中、回避値+3' },
      { id: 's7', name: 'マルチロックオン', level: 1, effect: 'マイナー。4MP。攻撃を範囲に' },
      {
        id: 's8',
        name: 'ファントムウェーブ',
        level: 1,
        effect: 'セット。3MP。「中」の単体と【知力】対決。スタンを与える',
      },
    ],
    equipment: {
      ...INITIAL_CHARACTER.equipment,
      rHand: {
        name: 'スタッフ',
        weight: 5,
        hitMod: -1,
        damage: '+2',
        range: '至近',
        dodgeMod: 0,
        defenseMod: 0,
        magicDefense: 0,
        notes: '',
      },
      body: {
        name: 'ローブ',
        weight: 2,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
      guardian: {
        name: 'マナヴェール',
        weight: 0,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
    },
    items: [
      { id: 'i1', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
      { id: 'i2', name: 'ヒールポーション', weight: 1, quantity: 1, notes: '' },
      { id: 'i3', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
    ],
  },

  // 4. マーシャルダンサー
  {
    ...INITIAL_CHARACTER,
    id: 'sample04',
    playerName: 'サンプル',
    characterName: 'マーシャルダンサー',
    isCopyProhibited: true,
    species: 'therian',
    style: 'shapeshifter',
    element: 'earth',
    hp: { modifier: 0 },
    mp: { modifier: 0 },
    wp: { modifier: 0 },
    gl: 0,
    abilities: {
      physical: { bonus: 0, otherModifier: 0, total: 6 },
      intellect: { bonus: 0, otherModifier: 0, total: 2 },
      mystic: { bonus: 0, otherModifier: 0, total: 4 },
      agility: { bonus: 0, otherModifier: 0, total: 5 },
      passion: { bonus: 0, otherModifier: 0, total: 2 },
      affection: { bonus: 0, otherModifier: 0, total: 2 },
    },
    combatValues: {
      magic: { modifier: 1 },
      dodge: { modifier: 0 },
      defense: { modifier: 0 },
    },
    specialChecks: {
      enemyLore: { modifier: 0 },
      appraisal: { modifier: 0 },
    },
    skills: [
      { id: 's1', name: 'マナインフロー', level: 0, effect: '魔術が使用可能になる' },
      {
        id: 's2',
        name: '種族スキル：獣族',
        level: 0,
        effect: '魔術判定後。ラウンド中、回避値に+3。シナリオ1回',
      },
      {
        id: 's3',
        name: 'ファージン',
        level: 0,
        effect: 'メジャー。1MP。焦点具で攻撃。ダメージ+2D',
      },
      {
        id: 's4',
        name: 'ソウルフィスト',
        level: 0,
        effect: 'DR前。6MP。ダメージに+8、貫通ダメージに',
      },
      { id: 's5', name: 'シェッドスキン', level: 1, effect: 'DR後。3MP。ダメージ(GL+1)D点軽減' },
      {
        id: 's6',
        name: 'ライフハーモニー',
        level: 0,
        effect: 'セット/マイナー。1MP。自身のHPを2D+5点回復',
      },
      {
        id: 's7',
        name: 'バタフライフロート',
        level: 1,
        effect: 'セット。4MP。ラウンド中、魔術値と回避値+2',
      },
      {
        id: 's8',
        name: 'ファンタジスタ',
        level: 1,
        effect: 'セット。4MP。「中」の単体と【俊】対決。パニックを与える',
      },
    ],
    equipment: {
      ...INITIAL_CHARACTER.equipment,
      rHand: {
        name: 'グローブ',
        weight: 1,
        hitMod: 1,
        damage: '+2',
        range: '至近',
        dodgeMod: 0,
        defenseMod: 0,
        magicDefense: 0,
        notes: '',
      },
      body: {
        name: 'ローブ',
        weight: 2,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
      guardian: {
        name: 'マナヴェール',
        weight: 0,
        hitMod: 0,
        damage: '',
        range: '',
        dodgeMod: 0,
        defenseMod: 2,
        magicDefense: 0,
        notes: '',
      },
    },
    items: [
      { id: 'i1', name: 'ヒールポーション', weight: 1, quantity: 1, notes: '' },
      { id: 'i2', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
      { id: 'i3', name: 'マナストーン(小)', weight: 1, quantity: 1, notes: '' },
    ],
  },
];
